// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vflnlraekakpltsuchhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmbG5scmFla2FrcGx0c3VjaGh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3ODA1OTgsImV4cCI6MjA1NTM1NjU5OH0.l9s1YhqlD8NrKEaXa-bWRbSgoERzB1lNbcRFHnvpOJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);